### ISSUE TITLE
Create fragment URL for `Ready To Start Building` section on https://www.loginradius.com/docs/developer/

### ISSUE THREAD

**Issue by IArchna** [LoginRadius/docs#267]
- When used, this fragment URL should land user to `Ready To Start Building` section 
- Fragment URL should look like: https://www.loginradius.com/docs/developer/#getstarted
- Fragment URL Reference that exists for API section- https://www.loginradius.com/docs/developer/#api

**Comment by JubayerJoy** [comment]
Hi @IArchna, I'd love to work on this issue. 
Please assign, cheers🎈

**Comment by IArchna** [comment]
@JubayerJoy  I have assigned this issue to you. Please proceed and submit PR when it's ready.

**Comment by JubayerJoy** [comment]
Hi @IArchna, this issue was resolved via #311
Please close this.
cheers.

**Comment by IArchna** [comment]
Thanks for contributing. Your PR is accepted for the Hacktoberfest. Please fill this [form](https://forms.gle/qhG6Sf8qrBznRrtQA) to become eligible for LoginRadius cool swags. :) @JubayerJoy
