### ISSUE TITLE
 Support for detailed table of content on right sidebar by including h3 tag as heading

### ISSUE THREAD

**Issue by aman-agrwl-zz** [LoginRadius/docs#29]
Support for detailed table of content on right sidebar by including h3 tag as heading

**Comment by ShubhamPalriwala** [comment]
Hey ! I'd like to resolve this issue !
Can you show some more light on what exactly is to be done ?

**Comment by mohammed786** [comment]
Hi Shubham, 

Currently, in any of our docs, the table of content is auto-generated till `h2`, we need to show the heading of `h3` as well in the auto-generated table of content.

In [this](https://www.loginradius.com/docs/developer/sdk-libraries/html5-library/) doc, the right side table is showing till **API Details**, we need to show **Authentication API** as well. 

I hope you got the issue now.

**Comment by ShubhamPalriwala** [comment]
Alright @mohammed786 , I'd like to resolve this issue in the HacktoberFest if you're okay with it !

**Comment by mohammed786** [comment]
Sure @ShubhamPalriwala, this issue is assigned to you.

And LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by sohamsshah** [comment]
Hello, @mohammed786 Is there any current issue that I can work on? Would love to contribute to LoginRadius.

**Comment by Harshsngh07** [comment]
Hi @mohammed786 any new issue that I can work on?

**Comment by HeroicHitesh** [comment]
@aman-agrwl @mohammed786 I see this is not being worked upon till now. So, I am taking it up.
