### ISSUE TITLE
Security: High Risk Vulnerabilities in current npm packages

### ISSUE THREAD

**Issue by ShubhamPalriwala** [LoginRadius/docs#30]
On local installation of the project, npm had reported 1751 vulnerabilities:
- 8 High 
- 2 Moderate 
- 1741 Low

On running `npm audit fix`, it fixed 1746 of them however 5 of them need to be manually reviewed.

These vulnerabilities could lead to Remote Memory Exposure, Signature Malleability, Prototype Pollution, Regular Expression Denial of Service

**Comment by ShubhamPalriwala** [comment]
Please suggest and I would like to work on this !

**Comment by vyasriday** [comment]
@ShubhamPalriwala Thanks for mentioning but there is actually nothing to do in this I think.

**Comment by ShubhamPalriwala** [comment]
Yeah but if you want i can have a look at the vulnerabilities that require manual reviews and try to fix them, if it makes sense
