### ISSUE TITLE
Link CONTRIBUTING.md to README.md

### ISSUE THREAD

**Issue by imanishbarnwal** [LoginRadius/docs#39]
So that it will easier for contributors to find it on README.md

**Comment by frbio** [comment]
I can work on this issue. Can you assign me?

**Comment by imanishbarnwal** [comment]
Hi, @frbio I had already done this just waiting to get PR merge.

**Comment by Shaddamah** [comment]
#54 Oh look like i've done the same update as yours, i'm sorry
